### PR TITLE
Reconnect now

### PR DESCRIPTION
**Pull request by de-git**
(This replaced my previous pull request)

The current reconnect method is just closing the socket and waiting for the reconnect timeout to happen.
I've added a new reconnectNow method that reconnects 'immediately'.
It also can be used to connect if the connection is currently closed.

Both could also happen within the reconnect method instead but I wasn't sure whether the existing behaviour was intentional.

### CODE REVIEW

**Comment by knalli** [comment]
Again, please follow https://github.com/knalli/angular-vertxbus/blob/master/CONTRIBUTING.md#contributingsubmitting-changes

**Comment by de-git** [comment]
Okay, I branched off canary but realised the pull request went out to master.
Is that what you mean?
Also the commit comment doesn't show up here. I can put that in the description.
Do you care about the single quotes?
Was there anything else before I submit a new pull request?

**Comment by knalli** [comment]
> Okay, I branched off canary but realised the pull request went out to master.
Is that what you mean?

Yes.

Additionally, there should be no need for a merge commit in you branch. And all commits should be squashed into a single one.

> Do you care about the single quotes?

Yes, the hound is correct. Also it should be notified by the `grunt jshint` command.

**Comment by knalli** [comment]
Only the "Line is too long." messages are too extreme (in tests), I will fix this later.

**Comment by de-git** [comment]
>Additionally, there should be no need for a merge commit in you branch. And all commits should be >squashed into a single one.
Okay, I thought I amended my commit. Obviously not quite. I will see how I can fix that.

>Yes, the hound is correct. Also it should be notified by the grunt jshint command.
That doesn't show me anything (only "2 files lint free.").

>Only the "Line is too long." messages are too extreme (in tests), I will fix this later.
What about in wrapper.coffee? I already had made it shorter and the longest line is now 86 characters long.

**Comment by knalli** [comment]
> What about in wrapper.coffee? I already had made it shorter and the longest line is now 86 characters long.

It's okay. 

> That doesn't show me anything (only "2 files lint free.").

Hm, will have a look into this.

**Comment by de-git** [comment]
This pull request has now been superseded and can be closed.

**Pull request closed without merging**
